server:
  port: ${port}

eureka:
  instance:
    hostname: ${name}
  client:
    service-url: 
      default-zone: http://${eureka.instance.hostname}:${server.port}
    fetch-registry: false
    register-with-eureka: false