server:
  port: ${port}
 
#specify the path to the repo that has the config files 
spring:
  cloud:
    config:
      server:
        git:
           username: ${username}
           password: ${password}
           uri: https://github.com/04Pravin/BACKEND-SOLR-STUDENT/
           default-label: main
           
          